-- Legacy compatibility file.
-- The canonical MatHero production schema now lives in:
--   supabase/migrations/001_initial_schema.sql
--
-- Seed data lives in:
--   supabase/seed.sql
--
-- Keep this file only as a pointer for older setup instructions.
